name: Deploy to Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy_api:
    runs-on: windows-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          # Add any additional setup commands

      - name: Deploy API
        run: |
          mlflow models serve -m mlflow_model --host 127.0.0.1 --port 8001
        background: true

  deploy_dashboard:
    runs-on: windows-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          # Add any additional setup commands

      - name: Deploy Dashboard
        run: |
          streamlit run dashboard.py

# Si l'on souhaite que ces deux jobs s'exécutent en parallèle, on peut le spécifier dans une matrice
deploy:
  needs: [deploy_api, deploy_dashboard]
